#spring.application.name=hexagonal
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal

hexagonalmock:
  client:
    address:
      url: http://localhost:8082/addresses